
APPL_COBJS += ACOT_debug.o ACOT_test.o ACOT_light_sensor.o ACOT_wheel.o
APPL_COBJS += ACOT_gyro_sensor.o EV3_balancer.o EV3_balancer_param.o
APPL_COBJS += ACOT_balancer.o ACOT_PID_control.o ACOT_button.o ACOT_run_style.o
APPL_COBJS += ACOT_tail.o ACOT_tail_control.o ACOT_bluetooth.o ACOT_calibration.o
APPL_COBJS += ACOT_ultrasonic_sensor.o ACOT_distance_estimation.o
APPL_COBJS += ACOT_speed_run.o ACOT_start.o ACOT_game_run.o ACOT_garage.o
APPL_COBJS += ACOT_seesaw.o ACOT_lookup.o ACOT_ET_2018.o